### ISSUE TITLE
Support for 1.21.9

### ISSUE THREAD

**Issue by MythMega** [Imprex-Development/zero-inventory-problems#47]
### Description

Plugin doesnt work on 1.21.9 while it's working on 1.21.8.
I'm using the last version (1.0.20)

### Reproduction Steps

Start a server with paper 1.21.9

### Expected Behaviour

run without error and allow us to open backpack as before

### Server Details

Paper-1.21.9-Build-55

### Zero Inventory Problems Version

1.0.20

### Logs and Configs

```
[20:21:51] [Server thread/INFO]: [ZeroInventoryProblems] Enabling ZeroInventoryProblems v1.0.20
[20:21:51] [Server thread/INFO]: [bukkit.zeroinventoryproblems] [ZeroInventoryProblems] Searching NMS adapter for server version "v1_21_R5"!
[20:21:51] [Server thread/ERROR]: Error occurred while enabling ZeroInventoryProblems v1.0.20 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R5/inventory/CraftItemStack
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.21.9.jar:1.21.9-55-b3d2158]
	at zip-plugin-1.0.20.jar/net.imprex.zip.NmsInstance.initialize(NmsInstance.java:31) ~[zip-plugin-1.0.20.jar:?]
	at zip-plugin-1.0.20.jar/net.imprex.zip.BackpackPlugin.onEnable(BackpackPlugin.java:47) ~[zip-plugin-1.0.20.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.9.jar:1.21.9-55-b3d2158]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.9.jar:1.21.9-55-b3d2158]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.9.jar:1.21.9-55-b3d2158]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[paper-1.21.9.jar:1.21.9-55-b3d2158]
	at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:590) ~[paper-1.21.9.jar:1.21.9-55-b3d2158]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:368) ~[paper-1.21.9.jar:1.21.9-55-b3d2158]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.9.jar:1.21.9-55-b3d2158]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:353) ~[paper-1.21.9.jar:1.21.9-55-b3d2158]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R5.inventory.CraftItemStack
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:208) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:175) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 18 more
[20:21:51] [Server thread/INFO]: [ZeroInventoryProblems] Disabling ZeroInventoryProblems v1.0.20
```

**Comment by NgLoader** [comment]
Builds currently running
